
#Data Importing
```{r}
setwd("C:/Nupur Rathi/TimeSeriesForecating")
fancyData<-read.csv("fancy.csv",header=FALSE)
colnames(fancyData)<-"Sales"

```

#Understanding Data
```{r}
dim(fancyData)
names(fancyData)
head(fancyData,20)
#Check for missing sales
sum(is.na(fancyData$Sales))
plot(fancyData$Sales)

```


#Converting to time series data and decomposing
```{r}
fancyData.ts<-ts(fancyData,start=1987,frequency = 12)
fancyData.ts
library(ggplot2)
library(forecast)
ggmonthplot(fancyData.ts, col="Blue")
ggseasonplot(fancyData.ts, main="Time Series Season Plot")

#Plotting the time series
plot(fancyData.ts/1000,main="Time Series Plot", ylab="Sales (in thousands)", xlab="Years", col="Blue")

#Dividing the time series data
decomposition=decompose(fancyData.ts,type="m")
#plot(decompose(fancyData.tstype="m"))
plot(decomposition, col="Blue")
```

#test for stationary
```{r}
library(tseries)
adf.test(fancyData.ts)

adf.test(diff(fancyData.ts))
```



#Splitting the data into test and train 
```{r}
fancyData.ts
fancyData.train=window(fancyData.ts,end=c(1991,12))
fancyData.train

fancyData.test=window(fancyData.ts,start=c(1992,1))
fancyData.test
```



#Holt Winter Model Creation

```{r}
library(forecast)
?hw()
Hw_Model=hw((fancyData.train))
Hw_Model
summary(hw((fancyData.train),seasonal="m",h=24))
plot(summary(hw((fancyData.train),seasonal="m")))

#two years forecast by Holtwinters model
fancyData.forecast=(hw((fancyData.train),seasonal="m",h=24)$mean)

fancyData.forecast
#lets compare with actual values in test data
plot(fancyData.test)
lines(fancyData.forecast,col=3)

accuracy(fancyData.forecast,fancyData.test)

#have to check tuning parameters for hw which can increase the accuracy
residual=fancyData.forecast-fancyData.test
#sum(residual)
acf(residual, lag.max=20)
Box.test(residual,lag=20,type="Ljung-Box")
```



```{r}
library(TSstudio)
#install.packages("TSstudio")
fancyData_train=log(fancyData.train)
hw_grid_shallow <- ts_grid(ts.obj = fancyData_train,
                            periods = 4,
                            model = "HoltWinters",
                            optim = "MAPE",
                            window_space = 6,
                            window_test = 12,
                            hyper_params = list(alpha = seq(0.01, 1,0.1),
                                                beta =  seq(0.01, 1,0.1),
                                                gamma = seq(0.01, 1,0.1)),
                            parallel = TRUE,
                            n.cores = 8)
 
 
 # Use the parameter range of the top 20 models 
 # to set a narrow but more agressive search
 
 a_min <- min(hw_grid_shallow$grid_df$alpha[1:20])
 a_max <- max(hw_grid_shallow$grid_df$alpha[1:20])
 
 b_min <- min(hw_grid_shallow$grid_df$beta[1:20])
 b_max <- max(hw_grid_shallow$grid_df$beta[1:20])
 
 g_min <- min(hw_grid_shallow$grid_df$gamma[1:20])
 g_max <- max(hw_grid_shallow$grid_df$gamma[1:20])
 
 hw_grid_second <- ts_grid(ts.obj = fancyData.train,
                           periods = 4,
                           model = "HoltWinters",
                           optim = "MAPE",
                           window_space = 6,
                           window_test = 12,
                           hyper_params = list(alpha = seq(a_min, a_max,0.05),
                                               beta =  seq(b_min, b_max,0.05),
                                               gamma = seq(g_min, g_max,0.05)),
                           parallel = TRUE,
                           n.cores = 8)
 
 md <- HoltWinters(fancyData_train, 
                   seasonal="m",
                   alpha = hw_grid_second$alpha,
                   beta = hw_grid_second$beta,
                   gamma = hw_grid_second$gamma)
 
```


```{r}
##Making forecast for the Test Data from the Tuned Holt Winters Model
#plot_forecast(fc)
forecast_grid=exp(forecast(md,h=24)$mean)
forecast_grid
hw_grid_second$alpha
hw_grid_second$beta
hw_grid_second$gamma
accuracy(forecast_grid,fancyData.test)
plot(fancyData.test/1000,xlab="Years",ylab="Sales(in thousands)",main="Sales Forecast vs Actual Sales on Test Data")
lines(forecast_grid/1000,col=3)
#forecast_grid
#have to check tuning parameters for hw which can increase the accuracy
residual_grid=forecast_grid-fancyData.test
sum(residual_grid)
acf(residual_grid, lag.max=20)
Box.test(residual_grid,lag=20,type="Ljung-Box")
```


```{r}
#Method Defining the distribution of residual points with normal curve superimposed
plotForecastErrors <- function(forecasterrors)
{
# make a histogram of the forecast errors:
mybinsize <- IQR(forecasterrors)/4
mysd <- sd(forecasterrors)
mymin <- min(forecasterrors) - mysd*5
mymax <- max(forecasterrors) + mysd*3
# generate normally distributed data with mean 0 and standard deviation mysd
mynorm <- rnorm(10000, mean=0, sd=mysd)
mymin2 <- min(mynorm)
mymax2 <- max(mynorm)
if (mymin2 < mymin) { mymin <- mymin2 }
if (mymax2 > mymax) { mymax <- mymax2 }
# make a red histogram of the forecast errors, with the normally distributed
mybins <- seq(mymin, mymax, mybinsize)
hist(forecasterrors, col="red", freq=FALSE, breaks=mybins)
# freq=FALSE ensures the area under the histogram = 1
# generate normally distributed data with mean 0 and standard deviation mysd
myhist <- hist(mynorm, plot=FALSE, breaks=mybins)
# plot the normal curve as a blue line on top of the histogram of forecast
points(myhist$mids, myhist$density, type="l", col="blue", lwd=2)
}
```


```{r}
#Plotting the histogram of the residuals to check the distribution of errors
plotForecastErrors(residual_grid)

```


```{r}
#Making prediction for the five years in the future using Tuned Holt Winter's Method
log_fancyData.ts=log(fancyData.ts)
md5 <- HoltWinters(log_fancyData.ts, 
                   seasonal="m",
                   alpha = hw_grid_second$alpha,
                   beta = hw_grid_second$beta,
                   gamma = hw_grid_second$gamma)

forecast5=exp(forecast(md5,h=60)$mean)
#plot(fancyData.ts/1000)
#forecast5
#plot(forecast(md5,h=60))
plot(forecast(md5,h=60),main="Five Years Forecasting Using Holt Winter's", ylim=c(6,20), xlab="Years",ylab="No of Sales(on log scale)")
```


#ARIMA Model creation
```{r}
plot(fancyData.train)
auto.arima(fancyData.train)
forecast(arima(fancyData.train,order=c(1,0,0),seasonal = list(order=c(1,1,0),period=12)))

fancyData.forecast2=forecast(arima(fancyData.train,order=c(1,0,0),seasonal = list(order=c(1,1,0),period=12)))$mean

plot(forecast(arima(fancyData.train,order=c(1,0,0),seasonal = list(order=c(1,1,0),period=12))))



# Arima with  Multiplicative 
auto.arima(log(fancyData.train), trace=TRUE,test='kpss', ic="bic")

arimaModel2=arima(log(fancyData.train),order=c(1,1,0),seasonal = list(order=c(0,1,1),period=12))

logforecast=forecast(arimaModel2)$mean
logforecast
fancyData.forecast2=exp(logforecast)
plot(fancyData.test)
lines(fancyData.forecast2,col=3)

accuracy(fancyData.forecast2,fancyData.test)

#check for residuals pattern
Box.test(arimaModel2$residuals)
acf(arimaModel2$residuals)

```
```{r}
#Tuned Arima
arimaModel3=arima(log(fancyData.train),order=c(0,1,1),seasonal = list(order=c(0,1,1),period=12))

logforecast_3=forecast(arimaModel3)$mean
#logforecast_3
fancyData.forecast3=exp(logforecast_3)
fancyData.forecast3
plot(fancyData.test/1000, main="ARIMA(0,1,1)(0,1,1)[12] Forecasting On Test Data",xlab="Years",ylab="Sales(in thousands)")
lines(fancyData.forecast3/1000,col=3)
accuracy(fancyData.forecast3,fancyData.test)

#check for residuals pattern
Box.test(arimaModel3$residuals)
acf(arimaModel3$residuals)

```

```{r}
#Next Five Year Forecasting Using Tuned ARIMA Model
#Trainig the model on full data
train_data_arima=log(fancyData.ts)
arima5=arima(train_data_arima,order=c(0,1,1),seasonal = list(order=c(0,1,1),period=12))

#Forecasting next five years sales
arima_forecast5=exp(forecast(arima5,h=60)$mean)
arima_forecast5
plot(forecast(arima5,h=60),main="Five Years Forecasting Using ARIMA", xlab="Years",ylab="No. of Sales(in log scale)")
```








